import { useEffect,useRef,useState } from 'react';
import { View,Text,TextInput,Pressable,StyleSheet,ScrollView } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { supabase,ensureUser } from '../lib/supabase';

type Game={id:string;name:string;active_question_id:string|null;buzzer_open:boolean;status:string;code:string};
type Player={id:string;display_name:string;score:number;user_id:string};
export default function Room(){
 const {code}=useLocalSearchParams<{code:string}>();const label=String(code||'').toUpperCase();
 const [game,setGame]=useState<Game|null>(null);const [players,setPlayers]=useState<Player[]>([]);const [me,setMe]=useState<Player|null>(null);const meRef=useRef<Player|null>(null);const [name,setName]=useState('');const [clue,setClue]=useState('Waiting for the next clue…');const [msg,setMsg]=useState('Waiting for the host');const [winner,setWinner]=useState<string|null>(null);const [error,setError]=useState('');
 useEffect(()=>{meRef.current=me},[me]);
 useEffect(()=>{let ch:any;void (async()=>{try{await ensureUser();const {data:g,error}=await supabase.from('games').select('*').eq('code',label).single();if(error||!g)throw error||new Error('Room not found');setGame(g);await loadPlayers(g.id);if(g.active_question_id)await loadClue(g.active_question_id);ch=supabase.channel(`mobile:${g.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'games',filter:`id=eq.${g.id}`},async p=>{const ng=p.new as Game;setGame(ng);setWinner(null);setMsg(ng.buzzer_open?'Buzzer is live!':'Waiting for the host');if(ng.active_question_id)await loadClue(ng.active_question_id);else setClue('Waiting for the next clue…')}).on('postgres_changes',{event:'*',schema:'public',table:'game_players',filter:`game_id=eq.${g.id}`},()=>loadPlayers(g.id)).on('postgres_changes',{event:'INSERT',schema:'public',table:'buzz_winners',filter:`game_id=eq.${g.id}`},p=>{const id=String((p.new as any).player_id);setWinner(id);setMsg(id===meRef.current?.id?'YOU GOT IT!':'Buzz locked')}).subscribe();}catch(e:any){setError(e?.message||'Could not join room')}})();return()=>{if(ch)supabase.removeChannel(ch)}},[label]);
 async function loadPlayers(id:string){const {data}=await supabase.from('game_players').select('*').eq('game_id',id);const list=(data||[]) as Player[];setPlayers(list);const current=meRef.current;if(current){const mine=list.find(p=>p.id===current.id);if(mine)setMe(mine)}}
 async function loadClue(id:string){const {data}=await supabase.from('game_questions').select('prompt').eq('id',id).single();setClue(data?.prompt||'Clue ready')}
 async function join(){try{const u=await ensureUser(name);if(!game)return;const display=name.trim()||`Player-${u.id.slice(0,4)}`;const {data,error}=await supabase.from('game_players').upsert({game_id:game.id,user_id:u.id,display_name:display},{onConflict:'game_id,user_id'}).select().single();if(error)throw error;setMe(data as Player);meRef.current=data as Player;await loadPlayers(game.id)}catch(e:any){setError(e?.message||'Could not join') }}
 async function buzz(){if(!game?.buzzer_open||!game.active_question_id||!me||winner)return;setMsg('Sending buzz…');const {data,error}=await supabase.rpc('claim_buzz',{p_game_id:game.id,p_question_id:game.active_question_id,p_player_id:me.id});setMsg(error?error.message:data?.won?'YOU GOT IT!':'Someone beat you to it')}
 const canBuzz=!!game?.buzzer_open&&!!game.active_question_id&&!winner;const leader=[...players].sort((a,b)=>b.score-a.score);
 if(error&&!game)return <View style={s.page}><Text style={s.error}>{error}</Text></View>;
 if(!me)return <View style={s.page}><Text style={s.kicker}>ROOM {label}</Text><Text style={s.title}>{game?.name||'Joining…'}</Text><View style={s.join}><Text style={s.label}>PLAYER NAME</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor="#526278" style={s.nameInput}/><Pressable style={s.joinBtn} onPress={join}><Text style={s.joinText}>Enter lobby</Text></Pressable>{error?<Text style={s.error}>{error}</Text>:null}</View></View>;
 return <ScrollView contentContainerStyle={s.scroll}><Text style={s.kicker}>ROOM {label}</Text><View style={s.top}><Text style={s.title}>{game?.name}</Text><View style={s.score}><Text style={s.scoreLabel}>SCORE</Text><Text style={s.scoreValue}>{me.score}</Text></View></View><Text style={s.clue}>{clue}</Text><View style={s.center}><Pressable disabled={!canBuzz} onPress={buzz} style={[s.buzz,canBuzz&&s.ready]}><Text style={[s.buzzText,canBuzz&&{color:'#fff'}]}>{canBuzz?'BUZZ':'WAIT'}</Text></Pressable><Text style={[s.msg,winner===me.id&&{color:'#5eead4'}]}>{winner?winner===me.id?'You buzzed first!':`${players.find(p=>p.id===winner)?.display_name||'Another player'} buzzed first`:msg}</Text></View><View style={s.board}><Text style={s.boardTitle}>Leaderboard</Text>{leader.map((p,i)=><View style={s.row} key={p.id}><Text style={s.rank}>{i+1}</Text><Text style={s.player}>{p.display_name}{p.id===me.id?' (you)':''}</Text><Text style={s.points}>{p.score}</Text></View>)}</View></ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#07111f',padding:24,paddingTop:55},scroll:{flexGrow:1,backgroundColor:'#07111f',padding:22,paddingTop:55,paddingBottom:45},kicker:{color:'#67e8f9',fontWeight:'900',letterSpacing:2,fontSize:12},title:{color:'#fff',fontWeight:'900',fontSize:31,marginTop:8,flex:1},join:{marginTop:40},label:{color:'#94a3b8',fontSize:12,fontWeight:'900',marginBottom:8},nameInput:{backgroundColor:'#0d1b2d',borderWidth:1,borderColor:'#29425f',borderRadius:15,padding:16,color:'#fff',fontSize:18},joinBtn:{backgroundColor:'#2dd4bf',padding:17,borderRadius:15,marginTop:12},joinText:{textAlign:'center',fontWeight:'900',fontSize:17,color:'#04111f'},error:{color:'#fda4af',marginTop:12},top:{flexDirection:'row',gap:12,alignItems:'center'},score:{backgroundColor:'#0d243c',borderWidth:1,borderColor:'#29425f',borderRadius:15,padding:10,minWidth:82,alignItems:'center'},scoreLabel:{color:'#94a3b8',fontSize:10,fontWeight:'800'},scoreValue:{color:'#facc15',fontSize:25,fontWeight:'900'},clue:{color:'#fff',fontSize:21,lineHeight:29,fontWeight:'800',textAlign:'center',minHeight:110,marginTop:30},center:{alignItems:'center',paddingVertical:24},buzz:{width:240,height:240,borderRadius:120,backgroundColor:'#4b1a27',borderWidth:10,borderColor:'#552b36',alignItems:'center',justifyContent:'center'},ready:{backgroundColor:'#e11d48',borderColor:'#fb7185'},buzzText:{fontSize:38,fontWeight:'900',color:'#8d5e6b'},msg:{color:'#cbd5e1',fontSize:18,fontWeight:'900',marginTop:24,textAlign:'center'},board:{backgroundColor:'#0d1b2d',borderWidth:1,borderColor:'#203651',borderRadius:18,padding:17,marginTop:15},boardTitle:{color:'#fff',fontWeight:'900',fontSize:18,marginBottom:8},row:{flexDirection:'row',alignItems:'center',paddingVertical:9,borderBottomWidth:1,borderBottomColor:'#1e324a'},rank:{color:'#67e8f9',width:28,fontWeight:'800'},player:{color:'#e2e8f0',flex:1,fontWeight:'700'},points:{color:'#facc15',fontWeight:'900'}})
