'use client';
import { useEffect,useMemo,useState } from 'react';
import { useParams } from 'next/navigation';
import { supabase } from '../../../lib/supabase';
import { ensureUser } from '../../../lib/auth';
import type { Game,GamePlayer,GameQuestion } from '@buzzboard/shared';

type Winner={player_id:string;question_id:string;buzz_round:number};
export default function PlayerRoom(){
 const {code}=useParams<{code:string}>(); const [game,setGame]=useState<Game|null>(null);const [question,setQuestion]=useState<GameQuestion|null>(null);const [players,setPlayers]=useState<GamePlayer[]>([]);const [me,setMe]=useState<GamePlayer|null>(null);const [display,setDisplay]=useState('');const [winner,setWinner]=useState<Winner|null>(null);const [message,setMessage]=useState('Waiting for the host');const [error,setError]=useState('');
 const sorted=[...players].sort((a,b)=>b.score-a.score);const winnerName=players.find(p=>p.id===winner?.player_id)?.display_name;
 const canBuzz=!!me&&!!game?.buzzer_open&&!!game.active_question_id&&!winner;
 useEffect(()=>{let channel:any;let mounted=true;void (async()=>{try{await ensureUser();const {data:g,error}=await supabase.from('games').select('*').eq('code',String(code).toUpperCase()).single();if(error||!g)throw error||new Error('Room not found');if(!mounted)return;setGame(g);await loadPlayers(g.id);if(g.active_question_id)await loadQuestion(g.active_question_id);channel=supabase.channel(`player:${g.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'games',filter:`id=eq.${g.id}`},async payload=>{const ng=payload.new as Game;setGame(ng);setWinner(null);setMessage(ng.buzzer_open?'Buzzer is live!':'Waiting for the host');if(ng.active_question_id)await loadQuestion(ng.active_question_id);else setQuestion(null)}).on('postgres_changes',{event:'*',schema:'public',table:'game_players',filter:`game_id=eq.${g.id}`},()=>loadPlayers(g.id)).on('postgres_changes',{event:'INSERT',schema:'public',table:'buzz_winners',filter:`game_id=eq.${g.id}`},payload=>{const w=payload.new as Winner;setWinner(w);setMessage(w.player_id===me?.id?'YOU GOT IT!':'Buzz locked')}).subscribe();}catch(e:any){setError(e?.message||'Could not join room')}})();return()=>{mounted=false;if(channel)supabase.removeChannel(channel)}},[code,me?.id]);
 async function loadPlayers(gameId:string){const {data}=await supabase.from('game_players').select('*').eq('game_id',gameId);setPlayers((data||[]) as GamePlayer[]);if(me){const mine=(data||[]).find((p:any)=>p.id===me.id);if(mine)setMe(mine as GamePlayer)}}
 async function loadQuestion(id:string){const {data}=await supabase.from('game_questions').select('*').eq('id',id).single();setQuestion(data as GameQuestion)}
 async function join(){try{const user=await ensureUser(display);if(!game)return;const name=display.trim()||`Player-${user.id.slice(0,4)}`;const {data,error}=await supabase.from('game_players').upsert({game_id:game.id,user_id:user.id,display_name:name},{onConflict:'game_id,user_id'}).select().single();if(error)throw error;setMe(data as GamePlayer);await loadPlayers(game.id)}catch(e:any){setError(e?.message||'Could not join') }}
 async function buzz(){if(!canBuzz||!game||!me)return;setMessage('Sending buzz…');const {data,error}=await supabase.rpc('claim_buzz',{p_game_id:game.id,p_question_id:game.active_question_id,p_player_id:me.id});if(error)setMessage(error.message);else setMessage(data?.won?'YOU GOT IT!':'Someone beat you to it')}
 if(error&&!game)return <main className="shell narrow"><div className="errorBox">{error}</div></main>;
 return <main className="shell playerShell"><div className="playerHeader"><div><div className="eyebrow">Room {String(code).toUpperCase()}</div><h1>{game?.name||'Joining…'}</h1></div>{me&&<div className="scoreBubble"><span>Your score</span><strong>{me.score}</strong></div>}</div>
 {!me?<section className="panel joinCard"><h2>Choose your player name</h2><input className="input" maxLength={24} value={display} onChange={e=>setDisplay(e.target.value)} placeholder="Kian"/><button className="btn wide" onClick={join}>Enter lobby</button></section>:<div className="playerLayout"><section className="buzzerPanel"><div className="clueMini">{question?question.prompt:'Waiting for the next clue…'}</div><button onClick={buzz} disabled={!canBuzz} className={`megaBuzz ${canBuzz?'ready':''}`}><span>{canBuzz?'BUZZ':'WAIT'}</span></button><div className={`buzzMessage ${winner?.player_id===me.id?'won':''}`}>{winnerName?(winner?.player_id===me.id?'You buzzed first!':`${winnerName} buzzed first`):message}</div></section><aside className="panel"><h3>Leaderboard</h3>{sorted.map((p,i)=><div className={`scoreRow ${p.id===me.id?'meRow':''}`} key={p.id}><span className="rank">{i+1}</span><span>{p.display_name}</span><strong>{p.score}</strong></div>)}</aside></div>}
 </main>
}
